name: Call Deploy release workflow

on:
  workflow_dispatch:
    inputs:
      merge-strategy:
        description: 'Merge strategy and strategy options. Used only in case of merge conflicts'
        required: false
        default: ''
        type: string
      release-version:
        description: 'Version number to use. If not provided will start with 0.1.0rc0 and use bump-rule to get to next version'
        required: false
        default: ''
        type: string
      bump-rule:
        description: 'Bump rule for computing next release version number.Used if no release-version is provided'
        required: false
        default: 'prerelease'
        type: choice
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
          - prerelease

defaults:
  run:
    shell: bash

env:
  LANG: en_US.utf-8
  LC_ALL: en_US.utf-8
  PYTHON_VERSION: '3.10'
  PROJECT_NAME: test-github-action-call-reusable

jobs:
  call-deploy-release:
    permissions:
      contents: write  # To push a branch
      pull-requests: write  # To create a PR from that branch

    uses: schandrika/github-tooling/.github/workflows/deploy-release.yml@main
    with:
      merge-strategy: ${{ inputs.merge-strategy }}
      release-version: ${{ inputs.release-version }}
      bump-rule: ${{ inputs.bump-rule }}
      run-tests-wait: 600
      publish-to-test-pypi: true
    secrets:
      git-token: ${{ secrets.GA_PAT_TOKEN }}
      pypi-token: ${{ secrets.TEST_PYPI_TOKEN }}

